repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
    -   id: check-docstring-first
    -   id: check-xml
    -   id: check-yaml
    -   id: debug-statements
    -   id: flake8
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v1.0.1
    hooks:
    -   id: reorder-python-imports
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v0.6.4
    hooks:
    -   id: add-trailing-comma
-   repo: https://github.com/chriskuehl/puppet-pre-commit-hooks
    rev: v2.0.1
    hooks:
    -   id: puppet-validate
    -   id: puppet-lint
        args: [
            --fix, --fail-on-warnings,
            --no-documentation-check,
            --no-arrow_on_right_operand_line-check,
        ]
-   repo: local
    hooks:
    -   id: rubocop
        name: rubocop
        entry: rubocop --auto-correct
        types: [ruby]
        language: ruby
        additional_dependencies: ['rubocop:0.52.0']
