AllCops:
  NewCops: enable
  TargetRubyVersion: '2.6'

Layout:
  Metrics/LineLength:
    IgnoreCopDirectives: true

Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Max: 30
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Max: 30
Naming/MethodParameterName:
  Enabled: false
